### ISSUE TITLE
I wish the Reactions plugin also with Mecha v1 CMS - :)

### ISSUE THREAD

**Issue by AlexL777** [mecha-cms/mecha#75]
Hi @tovic ,

I like to work with both Mecha CMS versions and with Mecha v1, I just asked myself whether it would not be possible to provide the new Reactions plugin for it.

Did you play with this idea or will not you do anything in this regard?

Reactions plugin I find simply cool and some blog readers just express their mood. I do not mind if there are a few negative reactions. So I know at least that the blog reader was angry or something in the article did not fit.

Then I wait for your feedback. Thanks in advance.

**Comment by tovic** [comment]
Working with legacy versions would be quite frustrating, as I am working with something that should be removed.

As how I have created the [/mecha-cms/0](https://github.com/mecha-cms/0) path, it is considered to be finished and I will not make any future features for this version.

Sometimes I wish that I can have more contributors for the extension/plugin/shield development so that people who have idea to convert Mecha V2&rsquo;s extension and plugin to make it work with Mecha V1 could publish their works for the community, but at the same time I also don&rsquo;t want this project becomes too big for some reasons.

**Comment by AlexL777** [comment]
I can understand all this and very bad, but I can not program PHP. I would like to be a developer, but my strength lies in installing CMS and creating blogs, forums, wikis and such projects.

I've already made advertising here and there for Mecha v2 and v1. Sorry, there are no more German Users of Mecha CMS. Very bad, but what can you do?

I look around in my own household and I can make a donation in some time. Every motivation is important and Mecha CMS I find super.

**Comment by tovic** [comment]
Oh no problem _sir_, it&rsquo;s fine. The Mecha CMS project itself was originally made privately by me used for my own purposes. But after I have finished the results, then I decided to make it open-source because I hope other people will use it too. You don&rsquo;t have to help me that far, having a user that want to help me to test it is already helpful, thank you very much. Especially for the last words.

As I know, most of the advertisements simply use services like Google or Facebook Ads to expand the audiences. But before this version gets stable, I can&rsquo;t start the advertising.

**Comment by tovic** [comment]
My next plan to make the users interested with this CMS is to make a PDF file contains basic guides for installing the CMS, it does not need to have much pages, just small overviews to give the users some clues about what they have to do with the downloaded files.

**Comment by AlexL777** [comment]
Such a PDF file might be interesting. This is already so.

A normal Wordpress Blogger will probably be overwhelmed with Mecha CMS if he has never used another CMS.

But this is the most interesting thing about Mecha CMS, that you can do a lot yourself and learn.
